name: Daily Run

on:
  schedule:
    - cron: '0 11 * * *'  # 16:00 Uhr Österreich Sommerzeit
  workflow_dispatch:        # ← diese Zeile

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Dependencies installieren
        run: npm install

      - name: Script ausführen
        run: node scripts/telegram.js   # ← deinen Script-Pfad anpassen
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}